[general]
# Run mode: both, rgb, mono
mode=both
# Disable tracking by default for inference-only mode
tracking=false

[can]
# CAN bus configuration for CANdle motor control
pan_node_id=16
tilt_node_id=18
datarate=1
max_velocity_rad_s=6.28
pds_node_id=100

[rgb]
camera_serial=41882813
camera_caps=video/x-raw(memory:NVMM),format=YUY2,width=4200,height=2160
infer_config=config/deepstream/config_infer_primary_rgb.txt
udp_host=123.69.69.53
udp_port=5001
encoder_bitrate=3000
muxer_width=1920
muxer_height=1088

[mono]
camera_serial=41882812
camera_caps=video/x-raw(memory:NVMM),format=GRAY8,width=4096,height=3000
infer_config=config/deepstream/config_infer_primary_yolov8.txt
udp_host=123.69.69.53
udp_port=5000
encoder_bitrate=5000
muxer_width=1920
muxer_height=1088
